repos:
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    - id: isort
      args: [--settings-path=./, ./]
      exclude: ^.*\b(venv)\b.*$

-   repo: https://github.com/ambv/black
    rev: 21.7b0
    hooks:
    - id: black
      args: [--config=./pyproject.toml, ./]
      exclude: ^.*\b(alembic)\b.*$
      language_version: python3.11

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
    -   id: mypy
        args: ["--config-file=./.mypy.ini", "--python-version=3.11"]
        exclude: ^.*\b(tests)\b.*$
        additional_dependencies:
          - "pydantic"
          - "types-requests"
          - "types-redis"
          - "types-croniter"
          - "types-pytz"
          - "types-cachetools"
          - "types-PyYAML"
          - "types-retry"
          - "types-Markdown"
          - "types-python-slugify"